"""
Bearer-token auth middleware.

Token lives at ~/.seren/secrets.json with {"agent_token": "..."}, chmod 600.
Generated by `seren-secrets.sh` which is invoked by foundation Phase 1
(or manually if missing).

Skipped paths:
    /                              - root info page (links only, no service data)
    /api/v1/system/ping            - liveness probe
    /api/v1/system/version         - agent version (no sensitive info)

Everything else requires `Authorization: Bearer <token>`.

When NO token is configured (fresh install before seren-secrets.sh runs),
the agent stays reachable for safe, read-only requests (GET/HEAD/OPTIONS) so
monitoring and bootstrap work - but it FAILS CLOSED on any state-changing
method (POST/PUT/PATCH/DELETE). This plane can restart services and trigger a
sudoers-backed reboot; an unprovisioned agent on 0.0.0.0 must never be an open
remote-reboot button. Provision the token to unlock mutating endpoints.

Threat model: this is a Jetson on your home LAN. The token protects against
casual LAN-mate snooping and prevents drive-by RCE if you ever expose the
agent port outside your trusted network. It is NOT designed for multi-user
or untrusted-attacker scenarios. Use a VPN or firewall if those apply.
"""
from __future__ import annotations

import hmac
import json
import os
from pathlib import Path

from fastapi import Request, Response
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.types import ASGIApp

SECRETS_PATH = Path(os.path.expanduser("~")) / ".seren" / "secrets.json"

# HTTP methods that don't change state. When no token is configured these
# stay open (read-only introspection for monitoring/bootstrap); everything
# else is refused until a token exists.
_SAFE_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})

# Paths that bypass auth. Keep this list MINIMAL - every entry here is an
# information disclosure or attack-surface concern.
PUBLIC_PATHS = frozenset({
    "/",
    "/api/v1/system/ping",
    "/api/v1/system/version",
})


def load_token() -> str | None:
    """Load the agent token from ~/.seren/secrets.json, or None if missing.

    None means "auth is disabled" - the agent will accept all requests. This
    is meant as a fallback for fresh installs before seren-secrets.sh runs;
    in production all installs should have a token.
    """
    if not SECRETS_PATH.is_file():
        return None
    try:
        with open(SECRETS_PATH) as f:
            data = json.load(f)
        token = data.get("agent_token")
        if isinstance(token, str) and token:
            return token
    except (json.JSONDecodeError, OSError):
        pass
    return None


class BearerAuthMiddleware(BaseHTTPMiddleware):
    """ASGI middleware that requires `Authorization: Bearer <token>` on
    every request EXCEPT those listed in PUBLIC_PATHS."""

    def __init__(self, app: ASGIApp, *, expected_token: str | None) -> None:
        super().__init__(app)
        self._expected = expected_token

    async def dispatch(self, request: Request, call_next) -> Response:
        path = request.url.path

        # If no token configured, stay reachable for safe reads but refuse
        # anything that changes state. The fresh-install convenience must not
        # extend to remote service restarts or a sudoers-backed reboot.
        if self._expected is None:
            if request.method not in _SAFE_METHODS:
                return JSONResponse(
                    {"error": "unauthorized",
                     "detail": "no agent token configured; service-management "
                               "endpoints are disabled until ~/.seren/secrets.json "
                               "exists (run seren-secrets.sh)"},
                    status_code=503,
                )
            response = await call_next(request)
            response.headers["X-Seren-Auth"] = "disabled-no-token-configured"
            return response

        if path in PUBLIC_PATHS:
            return await call_next(request)

        auth_header = request.headers.get("authorization", "")
        if not auth_header.startswith("Bearer "):
            return JSONResponse(
                {"error": "unauthorized", "detail": "missing bearer token"},
                status_code=401,
            )

        provided = auth_header[len("Bearer "):].strip()
        # Constant-time compare to avoid timing leaks on token prefix
        if not _constant_time_eq(provided, self._expected):
            return JSONResponse(
                {"error": "unauthorized", "detail": "invalid token"},
                status_code=401,
            )

        return await call_next(request)


def _constant_time_eq(a: str, b: str) -> bool:
    """Constant-time comparison via the stdlib's audited hmac.compare_digest.

    Encodes to bytes so non-ASCII input can't raise (compare_digest rejects
    non-ASCII str). Different-length inputs return False without raising, so
    this is a drop-in for the previous hand-rolled version - and it means we
    don't pull in the `cryptography` package just to compare two tokens.
    """
    return hmac.compare_digest(a.encode("utf-8"), b.encode("utf-8"))